// app/layout.jsx
import './globals.css';
import { Metadata } from 'next';
import Header from './Components/Header'
import { ContextProvider } from './Context/ContextAuth'
import { Inter } from '@fontsource/inter';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body>
        <ContextProvider>
          <div className="m-2 mx-5">
            <Header />
          </div>
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
